name: nightcore
main: su.nightexpress.nightcore.NightCore
version: '${project.version}'
description: Plugin Creation Kit.
author: NightExpress
api-version: 1.18
folia-supported: true
load: STARTUP
libraries:
  - com.zaxxer:HikariCP:5.0.1
  - it.unimi.dsi:fastutil-core:8.5.13