main: su.nightexpress.nightcore.NightCore
bootstrapper: su.nightexpress.nightcore.NightCoreBootstrap
loader: su.nightexpress.nightcore.NightCoreLoader
name: nightcore
version: '${project.version}'
description: Plugin engine
load: STARTUP
authors:
  - NightExpress
api-version: '1.19'
folia-supported: true
dependencies:
  server:
    Vault:
      required: false
      join-classpath: true
    LuckPerms:
      required: false
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true
    floodgate:
      required: false
      join-classpath: true
    CoinsEngine:
      required: false
    BeastTokens:
      required: false
    EliteMobs:
      required: false
    PlayerPoints:
      required: false
    UltraEconomy:
      required: false
    VotingPlugin:
      required: false
    ExcellentCrates:
      required: false
    ExecutableItems:
      required: false
    ItemsAdder:
      required: false
    MMOItems:
      required: false
    Nexo:
      required: false
    Oraxen:
      required: false