name: nightcore
main: su.nightexpress.nightcore.NightCore
version: '${project.version}'
description: Plugin core
author: NightExpress
api-version: 1.20
load: STARTUP
libraries:
  - com.zaxxer:HikariCP:6.3.2
  - it.unimi.dsi:fastutil-core:8.5.16
